os: osx
language: objective-c
osx_image: xcode10.1
install:
  - make dependencies
  - make generate
branches:
  only:
    - master
xcode_workspace: Canoe.xcworkspace
xcode_scheme: ApplicationTests
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone 8
